cmake_minimum_required(VERSION 3.20)

project(cabx-interpreter LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

file(GLOB_RECURSE SOURCES
	"${PROJECT_SOURCE_DIR}/src/*.cpp"
)

add_executable(cabx-interpreter
	${SOURCES}
)

target_include_directories(cabx-interpreter
	PRIVATE
		${PROJECT_SOURCE_DIR}/include
)